- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-optimiser-utility-evaluator-helm-lint
        - nebulous-optimiser-utility-evaluator-build-container-images
        - nebulous-optimiser-utility-evaluator-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-optimiser-utility-evaluator-helm-lint
        - nebulous-optimiser-utility-evaluator-upload-container-images
        - nebulous-optimiser-utility-evaluator-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    promote:
      jobs:
        - nebulous-optimiser-utility-evaluator-promote-container-images
