name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-optimiser-utility-evaluator:
    name: Build and push optimiser-utility-evaluator
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: utility-evaluator
      image-name: optimiser-utility-evaluator
    secrets: inherit
